/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20Contract } from "./Erc20Contract";

export { Erc20Contract__factory } from "./factories/Erc20Contract__factory";
